### ISSUE TITLE
[BUG] Due date is 1 month extra

### ISSUE THREAD

**Issue by IAmMilkyWayGalaxy** [Paymenter/Paymenter#468] opened 2024-06-27 06:22 UTC
**To Reproduce**
1. Buy a server with cash
2. After bought you can see that you purchased on 27.6.24 and it shows 27.8.24 as due date.

**Expected behavior**
It should only extend to a month not 2 months

**Screenshots**
![IMG_4803](https://github.com/Paymenter/Paymenter/assets/123291265/407d9c2a-0d97-431d-b932-d622762973d1)
![IMG_4804](https://github.com/Paymenter/Paymenter/assets/123291265/e92a0cc2-6eea-456a-827f-e4eb5d7d8e1c)

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser: Chrome
 - Version: 0.9.4

**Smartphone (please complete the following information):**
 - Device: IPhone 12
 - OS: IOS 17
 - Browser: Chrome
 - Version: 0.9.4

**Additional context**
In invoice it shows 27.7.24 but in customer area and in order details it shows 27.8.24

**Comment by IAmMilkyWayGalaxy** [comment] 2024-06-27 06:28
![Uploading IMG_4805.jpeg…]()

**Comment by IAmMilkyWayGalaxy** [comment] 2024-06-27 06:28
![IMG_4805](https://github.com/Paymenter/Paymenter/assets/123291265/a8edbab5-20e8-4335-bd85-207056961118)

**Comment by IAmMilkyWayGalaxy** [comment] 2024-07-01 17:25
still waiting for a response

**Comment by CorwinDev** [comment] 2024-07-01 17:33
I cannot reproduce, please respond with screenshots of the order before paying the invoice and after

**Comment by IAmMilkyWayGalaxy** [comment] 2024-07-01 17:43
Before paying 
![IMG_4827](https://github.com/Paymenter/Paymenter/assets/123291265/6dd85330-17e8-4700-a41a-9b2b80d5415f)
![IMG_4828](https://github.com/Paymenter/Paymenter/assets/123291265/1ef6c8a6-4e54-4018-8d00-b5c06755826b)

**Comment by IAmMilkyWayGalaxy** [comment] 2024-07-01 17:45
After paying 
![IMG_4830](https://github.com/Paymenter/Paymenter/assets/123291265/7ac96f8d-33c9-41a1-976b-95ab4fcd39ea)
![IMG_4831](https://github.com/Paymenter/Paymenter/assets/123291265/871bea48-a450-4bff-b8df-e46ad20b2d39)
![IMG_4832](https://github.com/Paymenter/Paymenter/assets/123291265/78789764-5ebd-4b17-a35e-429e1d648138)

**Comment by IAmMilkyWayGalaxy** [comment] 2024-07-01 17:48
> I cannot reproduce, please respond with screenshots of the order before paying the invoice and after

If you want a screen recorded video i can give

**Comment by IAmMilkyWayGalaxy** [comment] 2024-07-05 16:52
Again ded

**Comment by CorwinDev** [comment] 2024-07-05 17:05
Can you try removing setup fee and check if it happens again?

**Comment by IAmMilkyWayGalaxy** [comment] 2024-07-05 17:10
Yes it fixed the issue

**Comment by CorwinDev** [comment] 2024-07-05 17:58
Fixed in b0f1d104ec5207e76596ab59862fc7ff69388d06

**Closed by CorwinDev** 2024-07-05 17:58 UTC
